### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by GarimaPawar**
Review My Code

### CODE REVIEW

**Comment by sambit985** [comment]
Add `div` in line no. 133

**Comment by sambit985** [comment]
You can try also transform #css section

**Comment by GarimaPawar** [comment]
> Add `div` in line no. 133

@sambit985  ohh  i forgot close </div>........thanks for this information

**Comment by GarimaPawar** [comment]
> Add `div` in line no. 133

@sambit985  ohh  i forgot close </div>........thanks for this information

**Pull request merged**
